=== api-evangelist/argo/json-schema/argo-workflows-workflow-status-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/argo/refs/heads/main/json-schema/argo-workflows-workflow-status-schema.json",
  "title": "WorkflowStatus",
  "description": "Status of a workflow execution",
  "type": "object",
  "properties": {
    "phase": {
      "type": "string",
      "enum": [
        "Pending",
        "Running",
        "Succeeded",
        "Failed",
        "Error"
      ]
    },
    "startedAt": {
      "type": "string",
      "format": "date-time"
    },
    "finishedAt": {
      "type": "string",
      "format": "date-time"
    },
    "progress": {
      "type": "string",
      "description": "Progress of the workflow (e.g. 2/4)"
    },
    "message": {
      "type": "string"
    },
    "estimatedDuration": {
      "type": "integer"
    },
    "nodes": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/components/schemas/NodeStatus"
      }
    },
    "conditions": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string"
          },
          "status": {
            "type": "string"
          },
          "message": {
            "type": "string"
          }
        }
      }
    },
    "outputs": {
      "$ref": "#/components/schemas/Outputs"
    },
    "storedTemplates": {
      "type": "object"
    },
    "artifactRepositoryRef": {
      "type": "object",
      "properties": {
        "configMap": {
          "type": "string"
        },
        "key": {
          "type": "string"
        }
      }
    }
  }
}

=== api-evangelist/argo/examples/argo-workflows-workflow-status-example.json
{
  "phase": "Error",
  "startedAt": "example-value",
  "finishedAt": "example-value",
  "progress": "example-value",
  "message": "Completed successfully",
  "estimatedDuration": 52,
  "nodes": {},
  "conditions": [
    {
      "type": "example-value",
      "status": "Running",
      "message": "Completed successfully"
    },
    {
      "type": "example-value",
      "status": "Running",
      "message": "Completed successfully"
    }
  ],
  "outputs": "example-value",
  "storedTemplates": {},
  "artifactRepositoryRef": {
    "configMap": "example-value",
    "key": "example-value"
  }
}
